# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-22 15:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='file',
            new_name='doc',
        ),
    ]
